# Rename this file to languages.toml to enable multilingual support
[en]
    languageName = "English"
    contentDir = 'content/en'
    languagedirection = "ltr"
    title = "Zhou's blog"
    weight = 1
[zh]
    languageName = "Chinese"
    contentDir = 'content/zh'
    languagedirection = "ltr"
    title = "粥粥个人博客"
    weight = 2
