# Rename this file to languages.toml to enable multilingual support
[en]
    disabled = false
    languageName = "English"
    languageCode = 'en-US'
    languagedirection = "ltr"
    title = "Zhou's blog"
    weight = 1
[zh]
    disabled = false
    languageName = "简体中文"
    languageCode = 'zh-CN'
    languagedirection = "ltr"
    title = "粥粥个人博客"
    weight = 1
