# Configure main menu and social menu
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "Github"
url = "https://github.com/ZhouJump"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "bilibili"
url = "https://space.bilibili.com/346093756"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:x@zhoujump.club"

[social.params]
icon = "brand-email"

[[social]]
identifier = "rss"
name = "Subscribe to RSS"
url = "https://blog.zhoujump.club/en/index.xml"

[social.params]
icon = "brand-rss"
