# Configure main menu and social menu
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true
[[main]]
identifier = "comment"
name = "账户"
url = "https://comments.zhoujump.club/ui/profile"

[main.params]
icon = "user"
newTab = true

[[social]]
identifier = "github"
name = "Github"
url = "https://github.com/ZhouJump"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bilibili"
name = "哔哩哔哩主页"
url = "https://space.bilibili.com/346093756"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "email"
name = "电子邮件"
url = "mailto:x@zhoujump.club"

[social.params]
icon = "brand-email"

[[social]]
identifier = "rss"
name = "订阅RSS"
url = "https://blog.zhoujump.club/index.xml"

[social.params]
icon = "brand-rss"
