# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
[main.params]
icon = "home"
newtab = true

[[social]]
identifier = "gitlab"
name = "GitLab"
url = "https://gitlab.com/zhoujump"

[social.params]
icon = "brand-gitlab"

[[social]]
identifier = "bilibili"
name = "BiliBili"
url = "https://twitter.com"

[social.params]
icon = "brand-bilibili"
