# Configure main menu and social menu
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "gitlab"
name = "极狐仓库"
url = "https://gitlab.com/zhoujump"

[social.params]
icon = "brand-gitlab"

[[social]]
identifier = "bilibili"
name = "哔哩哔哩主页"
url = "https://space.bilibili.com/346093756"

[social.params]
icon = "brand-bilibili"

[[social]]
identifier = "email"
name = "电子邮件"
url = "mailto:x@zhoujump.club"

[social.params]
icon = "brand-email"

[[social]]
identifier = "rss"
name = "订阅RSS"
url = "https://blog.zhoujump.club/index.xml"

[social.params]
icon = "brand-rss"
