kind: pipeline
type: docker
name: blog

clone:
  git:
    environment:
      HTTP_PROXY: http://172.18.0.3:7890 
      HTTPS_PROXY: http://172.18.0.3:7890

steps:
  - name: setup
    image: hugomods/hugo:exts
    commands:
      - hugo mod tidy
      - hugo mod vendor

  - name: build
    image: hugomods/hugo:exts
    commands:
      - hugo

  - name: deploy
    image: nodeedgeone:latest
    environment:
      TEO_TOKEN:
        from_secret: TEO_PAGES_TOKEN
      PROJECT_NAME:
        from_secret: TEO_PROJECT
    commands:
      - edgeone pages deploy ./public -n "$PROJECT_NAME" -t "$TEO_TOKEN" --force
