kind: pipeline
type: docker
name: blog

steps:
  - name: build
    image: plugins/hugo
    settings:

  - name: deploy
    image: node:lts-alpine
    environment:
      TEO_TOKEN:
        from_secret: TEO_PAGES_TOKEN
      PROJECT_NAME:
        from_secret: TEO_PROJECT
    commands:
      - npm install -g edgeone
      - edgeone pages deploy ./public -n "$PROJECT_NAME" -t "$TEO_TOKEN" --force
