kind: pipeline
type: docker
name: blog

clone:
  git:
    environment:
      HTTP_PROXY: http://127.0.0.1:7890 
      HTTPS_PROXY: http://127.0.0.1:7890

steps:
  - name: setup
    image: hugomods/hugo:exts
    commands:
      - hugo mod tidy
      - hugo mod vendor

  - name: build
    image: hugomods/hugo:exts
    commands:
      - hugo

  - name: deploy
    image: node:lts-alpine
    environment:
      TEO_TOKEN:
        from_secret: TEO_PAGES_TOKEN
      PROJECT_NAME:
        from_secret: TEO_PROJECT
    commands:
      - npm install -g edgeone
      - edgeone pages deploy ./public -n "$PROJECT_NAME" -t "$TEO_TOKEN" --force

  - name: next  
    image: plugins/downstream
    settings:
      server: https://drone.zhoujump.club
      token:
        from_secret: DRONE_TOKEN
      repository: /ZhouJump/main-page@version2
