kind: pipeline
type: docker
name: blog

clone:
  retries: 8

steps:
  - name: setup
    image: hugomods/hugo:exts
    commands:
      - hugo mod tidy
      - hugo mod vendor

  - name: build
    image: hugomods/hugo:exts
    commands:
      - hugo

  - name: deploy
    image: nodeedgeone:latest
    pull: never
    environment:
      TEO_TOKEN:
        from_secret: TEO_PAGES_TOKEN
      PROJECT_NAME:
        from_secret: TEO_PROJECT
    commands:
      - edgeone pages deploy ./public -n "$PROJECT_NAME" -t "$TEO_TOKEN" --force

  - name: next  
    image: plugins/downstream
    settings:
      server: http://127.0.0.1:8080
      token:
        from_secret: DRONE_TOKEN
      repositories:
        - ZhouJump/main-page@version2
