kind: pipeline
type: docker
name: blog

steps:
  - name: setup
    image: klakegg/hugo
    commands:
      - hugo mod clean
      - hugo mod tidy
      - hugo mod vendor

  - name: build
    image: klakegg/hugo
    commands:
      - hugo

  - name: deploy
    image: node:lts-alpine
    environment:
      TEO_TOKEN:
        from_secret: TEO_PAGES_TOKEN
      PROJECT_NAME:
        from_secret: TEO_PROJECT
    commands:
      - npm install -g edgeone
      - edgeone pages deploy ./public -n "$PROJECT_NAME" -t "$TEO_TOKEN" --force
