paths:
  static: static
  uploads: static/uploads
timezone: Asia/Hong_Kong
markdown:
  engine: commonmark
  options:
    gfm: true
    linkify: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    breaks: false
    xhtml: false
    attributes: false
    typographer: false
    treat_indentation_as_code: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
collections_config:
  categories:
    path: content/categories
    icon: category
    glob:
      - '!_index.md'
  page:
    path: content/page
    icon: pace
    glob:
      - '!_index.md'
  post:
    path: content/post
    icon: event_available
    glob:
      - '!_index.md'
